version: '3.7'

services:
  postgres:
    container_name: 'postgres'
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: 'testing-api'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'testing'
    ports:
      - '5432:5432'

  testing-api:
    container_name: 'testing-api'
    image: ryanchristian4427/testing-api
    depends_on:
      - postgres
    ports:
      - '8000:8000'
